version: 2

project_name: miniclawd

builds:
  - main: ./main.go
    binary: miniclawd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/yifanes/miniclawd/cmd/miniclawd.version={{.Version}}

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

changelog:
  sort: asc

brews:
  - repository:
      owner: yifanes
      name: homebrew-tap
    homepage: https://github.com/yifanes/miniclawd
    description: Multi-platform AI chat bot
    license: MIT
    install: |
      bin.install "miniclawd"
    test: |
      system "#{bin}/miniclawd", "version"

release:
  github:
    owner: yifanes
    name: miniclawd
